version: "3"

services:

  rabbitmq:
    image: dev-rabbitmq
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: ./rabbitmq
    restart: ${RESTART}
    networks:
      - network

networks:

  network:
    external:
      name: ${NETWORK}
